import ContactMe from "./../../home/ContactMe";

export default function NewsOfTheDaiSupport({ contactMeRef }) {
  return (
    <>
      <div className="flex bg-zinc-800">
        <div className="pb-16 mx-auto container pt-3 px-6 max-w-screen-md">
          <h1 className="blog-heading">News Of The Dai</h1>
          <h1 className="blog-subheading">Support Information</h1>
          <p className="regular-paragraph">
            Thanks for downloading News Of The Dai!
          </p>
          <p className="regular-paragraph">
            If you are having any problems with the app, or want to make any
            suggestions for updates, please email me at{" "}
            <a
              href="mailto: hello@olivertoohey.com"
              className="text-white font-bold hover:text-yellow-100"
            >
              hello@olivertoohey.com
            </a>
            .
          </p>
          <p className="regular-paragraph">
            Please keep in mind that the content is generated by AI and
            therefore can sometimes be unpredictable!
          </p>
          <p className="regular-paragraph">
            The owners of the articles the app generates content from has no
            affiliation with the app, nor does the developer or owners of the
            articles take any responsiblity for the content generated.
          </p>
        </div>
      </div>
      <ContactMe contactMeRef={contactMeRef} />
    </>
  );
}
